# Generated by Django 3.0.2 on 2020-03-13 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0002_auto_20200305_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='News_content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('News_title', models.CharField(default='', max_length=50)),
                ('content', models.TextField(default='', max_length=1000)),
                ('image', models.ImageField(upload_to='')),
                ('video', models.CharField(default='', max_length=50)),
                ('news_category', models.TextField(default='', max_length=50)),
                ('status', models.TextField(default='', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
