# Generated by Django 3.0.2 on 2020-03-20 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
