# Generated by Django 3.0.2 on 2020-04-06 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_news_content_news_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_content',
            name='status',
            field=models.TextField(default='Pending', max_length=100),
        ),
    ]
