# Generated by Django 3.0.5 on 2020-05-11 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20200407_0409'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News_Status',
        ),
    ]
