# Generated by Django 3.0.2 on 2020-04-13 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments_data',
            old_name='data',
            new_name='comments_data',
        ),
    ]
