# Generated by Django 3.0.2 on 2020-04-13 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20200407_0409'),
        ('user', '0002_auto_20200414_0454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments_data',
            old_name='comments_data',
            new_name='data',
        ),
        migrations.RemoveField(
            model_name='comments_data',
            name='news_id',
        ),
        migrations.AddField(
            model_name='comments_data',
            name='news_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='news.News_content'),
            preserve_default=False,
        ),
    ]
