# Generated by Django 3.0.5 on 2020-05-02 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20200502_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
