# Generated by Django 3.0.5 on 2020-05-11 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20200502_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='updated_at',
        ),
    ]
