# Generated by Django 3.0.2 on 2020-03-08 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0002_auto_20200308_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_content',
            name='video',
            field=models.CharField(default='', max_length=50),
        ),
    ]
