# Generated by Django 3.0.2 on 2020-03-08 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0003_auto_20200308_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='news_content',
            name='status',
            field=models.TextField(default='Approval Pending from admin', max_length=100),
        ),
    ]
