# Generated by Django 3.0.2 on 2020-03-09 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0004_news_content_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_content',
            name='content',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='news_content',
            name='status',
            field=models.TextField(default='', max_length=100),
        ),
    ]
