# Generated by Django 3.0.2 on 2020-03-13 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_content'),
        ('admin1', '0006_auto_20200311_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_status',
            name='news_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='news.News_content'),
        ),
        migrations.DeleteModel(
            name='News_content',
        ),
    ]
