# Generated by Django 3.0.2 on 2020-03-13 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0007_auto_20200313_1240'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News_Status',
        ),
    ]
