# Generated by Django 3.0.2 on 2020-03-20 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0008_delete_news_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
