# Generated by Django 3.0.2 on 2020-03-20 20:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin1', '0010_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='profile',
            new_name='extended_user',
        ),
    ]
