# Generated by Django 3.0.2 on 2020-03-22 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0011_auto_20200321_0221'),
    ]

    operations = [
        migrations.DeleteModel(
            name='category',
        ),
    ]
