# Generated by Django 3.0.2 on 2020-04-05 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0013_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='extended_user',
            name='facebook',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='extended_user',
            name='instagram',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='extended_user',
            name='twitter',
            field=models.CharField(default='', max_length=250),
        ),
    ]
