# Generated by Django 3.0.2 on 2020-04-24 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0014_auto_20200405_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='extended_user',
            name='is_blocked',
            field=models.IntegerField(default='0'),
        ),
    ]
