# Generated by Django 3.0.2 on 2020-04-25 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0016_auto_20200424_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extended_user',
            name='is_blocked',
            field=models.CharField(default='Unblock', max_length=50),
        ),
    ]
